/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pixelartdev;

import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Deniz
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        helpScrollPane = new javax.swing.JScrollPane();
        helpTree = new javax.swing.JTree();
        contenScrolltPane = new javax.swing.JScrollPane();
        contentArea = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        setMinimumSize(new java.awt.Dimension(835, 345));
        setPreferredSize(new java.awt.Dimension(835, 345));

        SplitPane.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Help");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("First Start");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Check the Code");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Contribute");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Trouble Shooting");
        treeNode1.add(treeNode2);
        helpTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        helpTree.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        helpTree.setRootVisible(false);
        helpTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                helpTreeValueChanged(evt);
            }
        });
        helpScrollPane.setViewportView(helpTree);

        SplitPane.setLeftComponent(helpScrollPane);

        contentArea.setEditable(false);
        contentArea.setContentType("text/html"); // NOI18N
        contenScrolltPane.setViewportView(contentArea);

        SplitPane.setRightComponent(contenScrolltPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void helpTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_helpTreeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) helpTree.getLastSelectedPathComponent();
        
        switch (node.getUserObject().toString()) {
            case "First Start":
                contentArea.setText("<html><h1>First Start</h1><br>"
                        + "When you are using this tool for the first time, you need to enter"
                        + "your Envato username and your Api key and press save. When there now appears a green text saying saved, go ahead."
                        + "You will see below the settings a field to enter your purchase code. Just enter it there and press save."
                        + "In the box below that, the result will appear. For more information read the next chapter.");
                break;
            case "Check the Code":
                contentArea.setText("<html><h1>Check the Code</h1><br>"
                        + "You basicly have two options to enter the purchase codes:"
                        + "<ul><li>By just entering the code</li>"
                        + "<li>By entering mulitple codes at once</li></ul>"
                        + "If you just need to check one code, no problem, just enter it and press check."
                        + "But if you want to check multiple at once, then you can enter them in three (3) different ways:"
                        + "<ol><li>Enter all the codes you want to check sepperated by a space</li>"
                        + "<li>Enter all the codes you want to check sepperated by a comma (,)</li>"
                        + "<li>Enter all the codes you want to check sepperated by a semi colon (;)</li></ol>"
                        + "After entering just press check, and all codes will be listed there. Happy checking");
                break;
            case "Contribute":
                contentArea.setText("<html><h1>Contribute</h1><br>"
                        + "As this is an Open Source Project, you might help us to improve it and contribute to the project."
                        + "If you want to help, just visit the GitHub project page and improve the code or report bugs."
                        + "<a href=\"https://github.com/Pixelartdev/Envato-Purchase-Code-Checker\">GitHub</a>");
                break;
            case "Trouble Shooting":
                contentArea.setText("<html><h1>Trouble Shooting</h1><br>");
                break;
        }
    }//GEN-LAST:event_helpTreeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JScrollPane contenScrolltPane;
    private javax.swing.JTextPane contentArea;
    private javax.swing.JScrollPane helpScrollPane;
    private javax.swing.JTree helpTree;
    // End of variables declaration//GEN-END:variables
}
